<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<style>
.main_title{
  color:navy; 
  font-weight:bold;
  font-size:16px;  
}
.sub_title{
  color:red;
}
.info{
  color:blue;
}
</style>
<title>Terms of Use of HocalarBurada</title>
<body style='font-family:Arial;font-size:14px;'>
  <div style='max-width: 980px; margin: 0px auto; padding:10px; background-color: rgb(238, 238, 238); border: 4px double;'>
    <p align='center' style='font-size:16px;color:navy;'><b>Terms of Use of HocalarBurada</b></p>
    <p>These terms regulate the use of the hocalarburada.com.tr website. By visiting the site, or accepting the Terms of Use as a member of the hocalarburada.com.tr, users are restricted to this contract. If you do not agree with the terms of this agreement, you will use the hocalarburada.com.tr site and use the services provided.</p>
    <p>These terms of use are an ongoing agreement between you and hocalarburada.com.tr. You must read all the conditions carefully. The Terms apply to all users of the Service, including contributors to the Content. "Content" means any and all kinds of questions, texts, software, scripts, graphics, photographs, audio, music, video, audiovisual combinations and interactive materials.</p>
    <p>1- Terms of Use Amendment:<br>
    hocalarburada.com.tr reserves the right to amend the contract at any time without notice to the user. The most current version of this contract can be viewed on the "Terms of Use" link under the "About" tab of the hocalarburada.com.tr website. The most current version of the contract invalidates all previous contracts. Using the hocalarburada.com.tr website means you accept these changes.</p>
    <p>2- Site Content:<br>
    All material displayed on the Site (Questions, Texts, Images, Images and Videos) will be referred to as "Content" in this contract. The Site and its content are solely for the use of hocalarburada.com.tr users and may only be used in accordance with the terms of this agreement. (Inclusive content and applications provided by users) of all services, domain names, software codes, interfaces, content, product reviews, videos, algorithms, drawings, models, designs and all other intellectual property rights And other copyrights of the services offered are entirely owned by hocalarburada.com.tr. Users can not reproduce and distribute for profit by making any changes in the "content" or in whole. The site is available for individual users and may not be used for any commercial purpose. Organizations, companies and / or businesses may not use their site or services for any purpose. Content may not be copied and used for another product or service. The use of this site is subject to the terms and conditions of this Agreement.</p>
    <p>3- User Content:<br>
    User content refers to content created by a user himself and related to himself. Users are notified that they will donate their user content to hocalarburada.com.tr in a free and shared manner, permanently and permanently, worldwide, with free and transferable user rights (including related intellectual property rights) Their own benefit. Users acknowledge and agree that they will not use their rights in defamatory, degrading, obscene, pornographic, malicious, aggressive, or third party violations of rights and law. You are not entitled to remove any of the following rules: (1) You are not a member of any of these groups. Any user content from the Site. Below is a list of some of the illegal or prohibited things that should not be on the site. hocalarburada.com.tr reserves the right to investigate and violate those who violate these terms, to remove their membership, and to remove such inadvertent communication from the service. In addition, if hocalarburada.com.tr services and services are found to be in excess of their intended purpose, the hocalarburada.com.tr services should have the right to terminate immediately. In the direction of requests from judicial and administrative authorities, hocalarburada.com.tr is obliged to share information of illegitimate content and code owner. Prohibited points are: to disagree or to advocate for harassment of someone else; To engage in and act on behalf of any information or illegal activities or threatening, obscene, defamatory, derogatory or offensive conduct that a user finds to be false or misleading; Use illegal work or any other work without permission, such as using pirated computer programs or providing links to them, or providing information to circumvent any copy-protected devices that have been produced. Publish restricted or password-protected pages, or use hidden pages or images that do not contain or can be accessed from another page. Use informative content about illegal activities such as violating one's private life or providing or creating computer viruses; Obtain password or personal identity information from other users for commercial or illegal purposes; Racism, bigotry, content that encourages hate and physical harm to any individual or group. Although all of these things are prohibited, it is unlikely that a person will be exposed to such things, and there is a requirement that the User is obliged to abstain from exercising his / her rights with respect to damages from any party as a result of such exposure.</p>
    <p>4- Restrictions:<br>
    The user is responsible for all kinds of activities related to the services and access to the site. Any fraudulent, corrupt or otherwise illegal activity may be the reason for the user's right to access and access to the site to be terminated. The User can not post or transmit, or forward or post, any message or request to provide any password, account or personal information to any hocalarburada.com.tr user. It is strictly forbidden to use any site or service, to violate the security of any computer network, to break security encryption codes, to transfer or upload illegal materials containing threatening or obscene material, or to engage in any illegal activity. User; The Maillist, Listserv, or auto-call answerer can not upload any genre or 'spam' to the site that is run or actuated while the user is not logged in.</p>
    <p>5- Copyright Policy:<br>
    You may not add, distribute or copy any material, copyrighted material, trademark or other proprietary information in any form without the prior written consent of the owner of such proprietary rights. Persons who believe that an existing copyright has been infringed must pass the hocalarburada.com.tr contact page through the hocalarburada.com.tr website. Each user / member / visitor acknowledges that it is primarily responsible for the content produced or shared by him / her. According to the law no. 5651, the content provider (ie anyone who enters any content into hocalarburada.com.tr) is responsible for any content that it uses on the internet. In addition, the content provider is not responsible for the content that someone else has linked to. However, it is the responsibility of the general terms of the content provider to use the content it links to and to make it clear that the user intends to access the content in question. The user is responsible for the content of the hocalarburada.com.tr content and messages entered by him using the hocalarburada.com.tr site and its services, and for the entered content, messages, attachments and uploads. Net exclusively, unrestricted, worldwide, irrevocable and collective license and license. By using the hocalarburada.com.tr site and its services, the user is deemed to have granted exclusively, unrestricted, worldwide, irrevocable and bilateral permission and license to the hocalarburada.com.tr in connection with the content, messages, attachments and uploads created by him. The right to use the license and the right to use the license is subject to the terms of use, dissemination, reproduction, alteration, correction, adaptation, storage, processing and compilation of the contents provided and distributed by the user, distribution, transmission, retransmission, Lease, sell and other similar rights, as well as the right to license others in respect of such rights. Under the copyright policy of HocalarBurada, users who are found to be in breach of the HocalarBurada art court will lose access to the Service. This is a user who has been infected more than twice because of the infringement.</p>
    <p>6- Registration and Security:<br>
    As a condition of the use of the Services, the User must register with hocalarburada.com.tr and select a password and a Member Name hocalarburada.com.tr Member Name. The user must provide accurate, complete and current registration information to the hocalarburada.com.tr. Otherwise, this Agreement will be deemed to have been breached and the Account may be terminated without the User being informed.<br>
    The things a user can not do for sure are:<br>
    (1) can not select or use another person's name as a ExamReader.net Member Name in order to imitate a person<br>
    (2) You may not use a name that is legally owned by any person other than the User, without the necessary permission, as the hocalarburada.com.tr Member Name. Otherwise, hocalarburada.com.tr has the discretion to refuse registration or to cancel hocalarburada.com.tr Member Name. The user is obliged to protect the privacy of his own hocalarburada.com.tr password. hocalarburada.com.tr does not accept responsibility for the unauthorized use of this information and the use of the hocalarburada.com.tr services.<br></p>
    <p>7- Assurance:<br>
    The User shall not be liable to the hocalarburada.com.tr, its members, officers and employees; To pay damages, costs, attorneys' fees or indemnities arising out of access to the Site, use of the Services, violation of the User Agreement, or any other person or entity's infringement of intellectual property rights by the User or a third party using his / her account.</p>
    <p>8- Limitation of Liability:<br>
    hocalarburada.com.tr is not in any way responsible for (1) excessive user payments or (2) indirect damages for incidental or consequential damages arising out of or in connection with the Site or its services. Some states do not allow the exclusion or limitation of incidental or consequential damages; So the above restrictions may not apply to users in these countries. hocalarburada.com.tr will do its utmost to make sure that the services it offers run smoothly and without errors. However, technical failures that may occur in the systems of service providers providing internet access services, problems that may occur in the 3rd parties' systems, system maintenance and coercive causes may also be affected in connection with hocalarburada.com.tr services. In such cases, hocalarburada.com.tr will take the necessary measures to actively service the services, but does not accept any liability for any fault or malfunction of the connected service that is not directly intervening.</p>
    <p>9- Dispute Resolution<br>
    Any legal dispute that may arise between hocalarburada.com.tr and the user will first try to be resolved in good will, otherwise the parties agree that Istanbul Courts and Execution Offices are authorized. All use and disclosure rules are considered to be accepted by both parties as the user becomes a registered member, enters the site, starts using the content and services. The user or visitor can not claim that he or she has not been informed or has not read the contract. If the terms of use are not accepted, it is sufficient for the user not to use the site and services.</p>
    <p>10- Ending:<br>
    Either party may terminate the Services at any time upon notice to the other party on any occasion. In the event that the User violates any of the terms or conditions set forth in this agreement, hocalarburada.com.tr may immediately terminate or terminate access to some or all Services or the Site without prior notice. At the end of the User's account, the User's right to use the Services, access to the Site and any content immediately expires. The terms of this agreement will continue, without limitation, as a consequence of the end of the term, including the terms of ownership, waiver of guarantees and obligations.</p>
    <p>11- Other Provisions:<br>
    hocalarburada.com.tr may, at any time, change, abolish, or publish a new version of the user agreement at any time, subject to changing laws and conditions.</p>
    <p>Failure by any of the parties to enforce the provisions of the above-mentioned articles does not constitute a waiver of any other right. hocalarburada.com.tr is not responsible for failing to meet its obligations under this agreement due to faults caused by causes other than its own initiative such as mechanical, electronic or communicative breakdown or deterioration. If any provision of this contract is deemed to be unenforceable or invalid, then such invalidity shall be limited only to this condition and the remainder of the contract shall remain in full force and effect. This Agreement may not be transferred or assigned or licensed by the User without the written permission of hocalarburada.com.tr. hocalarburada.com.tr can cooperate in a variety of ways with many 3rd party organizations and organizations in order to make more effective use of the services and services they offer. This cooperation; Advertising, sponsorship, permitting marketing, data sharing, and other legal commercial methods. hocalarburada.com.tr declares and undertakes to provide the means to enable the user to leave the system free of charge and easily in the marketing activities with e-mail, that the user will be allowed to communicate in the manner prescribed by the law and that the user.</p>
	<p>The Turkish law shall apply to the relationship with hocalarburada.com.tr under the Terms and Conditions.The parties have exclusively authorized Turkish courts to resolve any legal matter arising from the Terms. However, you acknowledge that hocalarburada.com.tr may still apply to preventive measures (or other equivalent emergency remedies) around any jurisdiction.</p>

   </div>

</body>
</html>
	   